import Link from 'next/link';

export const metadata = {
  title: 'About Us | Phillips-David Model',
  description: 'Learn about the people, data, and process behind the Phillips-David Model.'
};

const pillars = [
  {
    number: '01',
    title: 'Roster Talent',
    text: 'Depth charts matter. The model builds team-level position groups from player talent and gives more influence to the players most likely to shape Saturdays.'
  },
  {
    number: '02',
    title: 'On-Field Performance',
    text: 'As a season develops, game results, efficiency, opponent context, and team tendencies help the ratings respond to what is actually happening on the field.'
  },
  {
    number: '03',
    title: 'Coaching Context',
    text: 'Coaching is treated as context, not magic. The model accounts for offensive and defensive influence, development, and the timing of a coach’s tenure.'
  }
];

export default function AboutPage() {
  return (
    <div className="about-page">
      <header className="about-hero">
        <div className="about-hero-copy">
          <div className="eyebrow">About Us</div>
          <h2>What is the PD Model?</h2>
          <p className="about-lead">
            The Phillips-David Model is an independent college football analytics project built by two 18-year-olds heading into college. What started as a shared interest in the sport has become a hands-on project we build, test, and improve in our spare time.
          </p>
          <p>
            Our goal is straightforward: create a useful way to compare teams, explore matchups, and track how the model performs as the season unfolds.
          </p>
        </div>
        <div className="about-brand-mark" aria-hidden="true">
          <img src="/brand/pd-logo.png" alt="" />
        </div>
      </header>

      <section className="about-intro-band" aria-labelledby="approach-heading">
        <div>
          <span className="eyebrow">Our Approach</span>
          <h3 id="approach-heading">Three inputs, one evolving view of each team.</h3>
        </div>
        <p>
          College football changes too quickly for one number to tell the whole story. The PD Model blends roster talent, in-season statistics, and coaching context, then tests those outputs against past results to keep the work grounded.
        </p>
      </section>

      <section className="about-pillar-grid" aria-label="What goes into the model">
        {pillars.map(pillar => (
          <article className="about-pillar" key={pillar.number}>
            <span>{pillar.number}</span>
            <h3>{pillar.title}</h3>
            <p>{pillar.text}</p>
          </article>
        ))}
      </section>

      <section className="about-detail-grid">
        <article className="about-detail-block">
          <span className="eyebrow">Player Ratings</span>
          <h3>Starting with talent, then putting it on one scale.</h3>
          <p>
            Player talent data begins with On3 roster ratings. We normalize and adjust that information so it can sit on the same scale as the rest of the model, then use position-specific depth weighting instead of treating every player on a roster the same.
          </p>
          <small>On3 is a data source only. The PD Model is independent and is not affiliated with or endorsed by On3.</small>
        </article>

        <article className="about-detail-block about-detail-accent">
          <span className="eyebrow">Built To Be Checked</span>
          <h3>Predictions should have a track record.</h3>
          <p>
            The model keeps its historical backtests visible so visitors can review game-by-game results, margin error, and how the model compared with the market. We care about making the model better, not pretending it is perfect.
          </p>
          <Link className="text-link" href="/backtest">Explore the backtest</Link>
        </article>
      </section>

      <section className="about-use-band">
        <div>
          <span className="eyebrow">Explore The Site</span>
          <h3>Use the model your way.</h3>
          <p>Browse the weekly team board, build a custom matchup, or look through the historical record behind the projections.</p>
        </div>
        <div className="about-link-row">
          <Link className="button-link primary" href="/ratings">Power Ratings</Link>
          <Link className="button-link" href="/predict">Matchup Lab</Link>
        </div>
      </section>

      <p className="about-footnote">
        The PD Model is a fan-built research project for entertainment and discussion. Ratings and projections are opinions generated by the model, not guarantees of future results.
      </p>
    </div>
  );
}
