-- Add the editable coaching configuration used by the ratings model.
-- Safe to run more than once.

create table if not exists public.coach_configs (
  id bigint generated by default as identity primary key,
  team text not null unique,
  coach_name text,
  tier text not null default 'Average' check (tier in ('Elite', 'Good', 'Average', 'Concerning', 'Unknown')),
  hire_year integer,
  off_tendency integer not null default 3 check (off_tendency between 1 and 5),
  def_tendency integer not null default 3 check (def_tendency between 1 and 5),
  preseason_override numeric,
  notes text,
  source text not null default 'manual',
  updated_at timestamptz not null default now()
);

insert into public.coach_configs (team)
select school from public.teams
where school is not null
on conflict (team) do nothing;

alter table public.coach_configs enable row level security;
grant select on public.coach_configs to anon, authenticated;
grant all privileges on public.coach_configs to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists "public read coach_configs" on public.coach_configs;
create policy "public read coach_configs"
  on public.coach_configs for select using (true);
