-- ============================================================
-- CFB MODEL APP SCHEMA - VERSION 3
-- ============================================================
-- This schema is for the no-Google-Sheets version.
-- Run it in Supabase SQL Editor.
-- ============================================================

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  school text not null unique,
  conference text,
  classification text,
  is_power boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  cfbd_game_id bigint unique,
  season integer not null,
  week integer not null,
  model_week integer,
  season_type text not null default 'regular',
  home_team text not null,
  away_team text not null,
  home_points integer,
  away_points integer,
  start_date timestamptz,
  neutral_site boolean default false,
  completed boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_game_stats (
  id bigint generated by default as identity primary key,
  game_id bigint references public.games(id) on delete cascade,
  cfbd_game_id bigint,
  season integer not null,
  week integer not null,
  model_week integer,
  season_type text not null default 'regular',
  team text not null,
  opponent text not null,
  is_home boolean,
  ppa_off numeric,
  ppa_def numeric,
  success_off numeric,
  success_def numeric,
  pts_per_drive_off numeric,
  pts_per_drive_def numeric,
  rush_ppa_off numeric,
  rush_ppa_def numeric,
  pass_ppa_off numeric,
  pass_ppa_def numeric,
  rush_rate_off numeric,
  pass_rate_off numeric,
  raw jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season, week, team, opponent)
);

create table if not exists public.roster_players (
  id bigint generated by default as identity primary key,
  season integer not null,
  team text not null,
  player_name text not null,
  position text,
  rating numeric,
  class_year text,
  source text default 'on3',
  raw jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season, team, player_name, position)
);

create table if not exists public.on3_roster_sources (
  id bigint generated by default as identity primary key,
  season integer not null,
  team text not null,
  url text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season, team)
);

create table if not exists public.coach_configs (
  id bigint generated by default as identity primary key,
  team text not null unique,
  coach_name text,
  tier text not null default 'Average' check (tier in ('Elite', 'Good', 'Average', 'Concerning', 'Unknown')),
  hire_year integer,
  off_tendency integer not null default 3 check (off_tendency between 1 and 5),
  def_tendency integer not null default 3 check (def_tendency between 1 and 5),
  offense_rating integer not null default 5 check (offense_rating between 1 and 10),
  defense_rating integer not null default 5 check (defense_rating between 1 and 10),
  development_rating text not null default 'Average' check (development_rating in ('Elite', 'Good', 'Average', 'Poor', 'Terrible')),
  preseason_override numeric,
  notes text,
  source text not null default 'manual',
  updated_at timestamptz not null default now()
);

create table if not exists public.model_configs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  pass_weight numeric not null default 0.30,
  rush_weight numeric not null default 0.20,
  overall_weight numeric not null default 0.25,
  composite_weight numeric not null default 0.25,
  points_per_rating numeric not null default 1.4,
  home_field numeric not null default 2.5,
  margin_shrink numeric not null default 0.75,
  max_margin numeric not null default 24.5,
  coach_offense_boost numeric not null default 0.6,
  coach_defense_boost numeric not null default 0.6,
  coach_development_boost numeric not null default 1.0,
  rating_recency_weight numeric not null default 2.5,
  rating_talent_weight numeric not null default 0.4,
  rating_historical_position_weight numeric not null default 0.3,
  rating_preseason_position_weight numeric not null default 0.7,
  rating_talent_ramp_weeks numeric not null default 8,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.model_configs (
  name,
  pass_weight,
  rush_weight,
  overall_weight,
  composite_weight,
  points_per_rating,
  home_field,
  margin_shrink,
  max_margin,
  coach_offense_boost,
  coach_defense_boost,
  coach_development_boost,
  rating_recency_weight,
  rating_talent_weight,
  rating_historical_position_weight,
  rating_preseason_position_weight,
  rating_talent_ramp_weeks,
  is_active
) values (
  'default',
  0.30,
  0.20,
  0.25,
  0.25,
  1.4,
  2.5,
  0.75,
  24.5,
  0.6,
  0.6,
  1.0,
  2.5,
  0.4,
  0.3,
  0.7,
  8,
  true
) on conflict (name) do nothing;

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  season integer not null,
  team text not null,
  off_rating numeric,
  def_rating numeric,
  composite numeric,
  off_rating_delta numeric,
  def_rating_delta numeric,
  composite_delta numeric,
  games integer,
  rush_off_rating numeric,
  pass_off_rating numeric,
  rush_def_rating numeric,
  pass_def_rating numeric,
  qb_rating numeric,
  rb_rating numeric,
  wr_rating numeric,
  te_rating numeric,
  ol_rating numeric,
  dl_rating numeric,
  lb_rating numeric,
  cb_rating numeric,
  s_rating numeric,
  k_rating numeric,
  p_rating numeric,
  pass_rate numeric,
  source text default 'app',
  synced_at timestamptz not null default now(),
  unique (season, team)
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null,
  home_team text not null,
  away_team text not null,
  model_spread text,
  model_home_margin numeric,
  predicted_favorite text,
  predicted_margin numeric,
  pass_adv numeric,
  rush_adv numeric,
  overall_adv numeric,
  composite_adv numeric,
  vegas_spread text,
  model_vegas_diff numeric,
  model_vegas_pick text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season, week, home_team, away_team)
);

create table if not exists public.backtest_games (
  id bigint generated by default as identity primary key,
  season integer not null,
  week integer not null,
  week_label text,
  home_team text not null,
  away_team text not null,
  vegas_spread text,
  model_spread text,
  model_vegas_diff numeric,
  model_vegas_pick text,
  model_vegas_result text,
  model_vegas_ats_margin numeric,
  home_pts integer,
  away_pts integer,
  home_margin integer,
  actual_result text,
  predicted_favorite text,
  predicted_margin numeric,
  model_home_margin numeric,
  actual_winner text,
  actual_win_margin numeric,
  margin_error numeric,
  error_bucket text,
  pick_result text,
  synced_at timestamptz not null default now(),
  unique (season, week, home_team, away_team)
  ALTER TABLE backtest_games 
  ADD COLUMN IF NOT EXISTS ml_home_margin FLOAT,
  ADD COLUMN IF NOT EXISTS ml_win_prob_home FLOAT;
);

create table if not exists public.backtest_summary (
  id bigint generated by default as identity primary key,
  season text not null,
  week text not null,
  games integer,
  picks_correct integer,
  picks_wrong integer,
  pick_pct numeric,
  avg_margin_error numeric,
  median_margin_error numeric,
  vegas_edge_plays integer,
  vegas_edge_wins integer,
  vegas_edge_losses integer,
  vegas_edge_pushes integer,
  vegas_edge_win_pct numeric,
  synced_at timestamptz not null default now(),
  unique (season, week)
);

create table if not exists public.weight_optimizer (
  id bigint generated by default as identity primary key,
  rank integer not null,
  use_this text,
  pass_weight numeric,
  rush_weight numeric,
  overall_weight numeric,
  composite_weight numeric,
  points_per_rating numeric,
  home_field numeric,
  margin_shrink numeric,
  max_margin numeric,
  coach_offense_boost numeric,
  coach_defense_boost numeric,
  coach_development_boost numeric,
  rating_talent_ramp_weeks numeric,
  train_score numeric,
  holdout_score numeric,
  all_score numeric,
  stability_penalty numeric,
  final_score numeric,
  synced_at timestamptz not null default now(),
  unique (rank)
);

create table if not exists public.model_buckets (
  id bigint generated by default as identity primary key,
  bucket_type text not null,
  bucket text not null,
  games integer,
  picks_correct integer,
  picks_wrong integer,
  pick_pct numeric,
  avg_margin_error numeric,
  median_margin_error numeric,
  synced_at timestamptz not null default now(),
  unique (bucket_type, bucket)
);

create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  status text not null,
  message text,
  metadata jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists idx_games_season_week on public.games (season, week);
create index if not exists idx_team_game_stats_season_team on public.team_game_stats (season, team);
create index if not exists idx_roster_players_season_team on public.roster_players (season, team);
create index if not exists idx_on3_roster_sources_season on public.on3_roster_sources (season, enabled);
create index if not exists idx_coach_configs_team on public.coach_configs (team);
create index if not exists idx_ratings_season_composite on public.ratings (season, composite desc);
create index if not exists idx_predictions_season_week on public.predictions (season, week);
create index if not exists idx_backtest_games_season_week on public.backtest_games (season, week);

alter table public.teams enable row level security;
alter table public.games enable row level security;
alter table public.team_game_stats enable row level security;
alter table public.roster_players enable row level security;
alter table public.on3_roster_sources enable row level security;
alter table public.coach_configs enable row level security;
alter table public.model_configs enable row level security;
alter table public.ratings enable row level security;
alter table public.predictions enable row level security;
alter table public.backtest_games enable row level security;
alter table public.backtest_summary enable row level security;
alter table public.weight_optimizer enable row level security;
alter table public.model_buckets enable row level security;
alter table public.job_runs enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select on all tables in schema public to anon, authenticated;
grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'teams',
    'games',
    'team_game_stats',
    'roster_players',
    'on3_roster_sources',
    'coach_configs',
    'model_configs',
    'ratings',
    'predictions',
    'backtest_games',
    'backtest_summary',
    'weight_optimizer',
    'model_buckets',
    'job_runs'
  ]
  loop
    execute format('drop policy if exists "public read %s" on public.%I', table_name, table_name);
    execute format('create policy "public read %s" on public.%I for select using (true)', table_name, table_name);
  end loop;
end $$;
