-- Seed coach names, legacy tiers, and hire years from the 2026 coach screenshots.
-- Run migrate-coach-ratings-and-formula-boosts.sql before this file.

with input(team, coach_name, legacy_tier, hire_year) as (
  values
    ('Air Force', 'Troy Calhoun', 'Average', null::integer),
    ('Akron', 'Joe Moorhead', 'Average', null::integer),
    ('Alabama', 'Kalen DeBoer', 'Average', 2024),
    ('App State', 'Dowell Loggains', 'Unknown', 2025),
    ('Arizona', 'Brent Brennan', 'Average', 2024),
    ('Arizona State', 'Kenny Dillingham', 'Good', 2023),
    ('Arkansas', 'Ryan Silverfield', 'Unknown', 2026),
    ('Arkansas State', 'Butch Jones', 'Average', null::integer),
    ('Army', 'Jeff Monken', 'Average', null::integer),
    ('Auburn', 'Alex Golesh', 'Unknown', 2026),
    ('BYU', 'Kalani Sitake', 'Average', null::integer),
    ('Ball State', 'Mike Uremovich', 'Unknown', 2025),
    ('Baylor', 'Dave Aranda', 'Average', null::integer),
    ('Boise State', 'Spencer Danielson', 'Average', 2024),
    ('Boston College', 'Bill O''Brien', 'Average', 2024),
    ('Bowling Green', 'Eddie George', 'Unknown', 2025),
    ('Buffalo', 'Pete Lembo', 'Good', 2024),
    ('California', 'Tosh Lupoi', 'Unknown', 2026),
    ('Central Michigan', 'Matt Drinkall', 'Good', 2025),
    ('Charlotte', 'Tim Albin', 'Average', 2025),
    ('Cincinnati', 'Scott Satterfield', 'Average', 2023),
    ('Clemson', 'Dabo Swinney', 'Average', null::integer),
    ('Coastal Carolina', 'Ryan Beard', 'Unknown', 2026),
    ('Colorado', 'Deion Sanders', 'Average', 2023),
    ('Colorado State', 'Jim Mora', 'Good', 2026),
    ('Delaware', 'Ryan Carty', 'Average', null::integer),
    ('Duke', 'Manny Diaz', 'Average', 2024),
    ('East Carolina', 'Blake Harrell', 'Good', 2025),
    ('Eastern Michigan', 'Chris Creighton', 'Average', null::integer),
    ('Florida', 'Jon Sumrall', 'Unknown', 2026),
    ('Florida Atlantic', 'Zach Kittley', 'Unknown', 2025),
    ('Florida International', 'Willie Simmons', 'Good', 2025),
    ('Florida State', 'Mike Norvell', 'Average', null::integer),
    ('Fresno State', 'Matt Entz', 'Good', 2025),
    ('Georgia', 'Kirby Smart', 'Elite', null::integer),
    ('Georgia Southern', 'Clay Helton', 'Average', null::integer),
    ('Georgia State', 'Dell McGee', 'Concerning', 2024),
    ('Georgia Tech', 'Brent Key', 'Average', 2023),
    ('Hawai''i', 'Timmy Chang', 'Average', null::integer),
    ('Houston', 'Willie Fritz', 'Elite', 2024),
    ('Illinois', 'Bret Bielema', 'Average', null::integer),
    ('Indiana', 'Curt Cignetti', 'Elite', 2024),
    ('Iowa', 'Kirk Ferentz', 'Average', null::integer),
    ('Iowa State', 'Jimmy Rogers', 'Unknown', 2026),
    ('Jacksonville State', 'Charles Kelly', 'Unknown', 2025),
    ('James Madison', 'Billy Napier', 'Unknown', 2026),
    ('Kansas', 'Lance Leipold', 'Average', null::integer),
    ('Kansas State', 'Collin Klein', 'Unknown', 2026),
    ('Kennesaw State', 'Jerry Mack', 'Elite', 2025),
    ('Kent State', 'Mark Carney', 'Average', 2025),
    ('Kentucky', 'Will Stein', 'Unknown', 2026),
    ('LSU', 'Lane Kiffin', 'Good', 2026),
    ('Liberty', 'Jamey Chadwell', 'Average', 2023),
    ('Louisiana', 'Michael Desormeaux', 'Average', null::integer),
    ('Louisiana Tech', 'Sonny Cumbie', 'Average', null::integer),
    ('Louisville', 'Jeff Brohm', 'Good', 2023),
    ('Marshall', 'Tony Gibson', 'Good', 2025),
    ('Maryland', 'Mike Locksley', 'Average', null::integer),
    ('Massachusetts', 'Joe Harasymiak', 'Concerning', 2025),
    ('Memphis', 'Charles Huff', 'Unknown', 2026),
    ('Miami', 'Mario Cristobal', 'Elite', null::integer),
    ('Miami (OH)', 'Chuck Martin', 'Average', null::integer),
    ('Michigan', 'Kyle Whittingham', 'Average', 2026),
    ('Michigan State', 'Pat Fitzgerald', 'Average', 2024),
    ('Middle Tennessee', 'Derek Mason', 'Average', 2024),
    ('Minnesota', 'P.J Fleck', 'Average', null::integer),
    ('Mississippi State', 'Jeff Lebby', 'Good', 2024),
    ('Missouri', 'Eli Drinkwitz', 'Average', null::integer),
    ('Missouri State', 'Casey Woods', 'Average', null::integer),
    ('NC State', 'Dave Doeren', 'Average', null::integer),
    ('Navy', 'Brian Newberry', 'Average', 2023),
    ('Nebraska', 'Matt Rhule', 'Good', 2023),
    ('Nevada', 'Jeff Choate', 'Average', 2024),
    ('New Mexico', 'Jason Eck', 'Good', 2025),
    ('New Mexico State', 'Tony Sanchez', 'Average', 2024),
    ('North Carolina', 'Bill Belichick', 'Concerning', 2025),
    ('North Texas', 'Neal Brown', 'Unknown', 2026),
    ('Northern Illinois', 'Rob Harley', 'Average', null::integer),
    ('Northwestern', 'David Braun', 'Average', 2024),
    ('Notre Dame', 'Marcus Freeman', 'Elite', null::integer),
    ('Ohio', 'John Hauser', 'Unknown', 2026),
    ('Ohio State', 'Ryan Day', 'Elite', null::integer),
    ('Oklahoma', 'Brent Venables', 'Good', null::integer),
    ('Oklahoma State', 'Eric Morris', 'Unknown', 2026),
    ('Old Dominion', 'Ricky Rahne', 'Average', null::integer),
    ('Ole Miss', 'Pete Golding', 'Good', null::integer),
    ('Oregon', 'Dan Lanning', 'Elite', null::integer),
    ('Oregon State', 'JaMarcus Sheppard', 'Unknown', 2026),
    ('Penn State', 'Matt Campbell', 'Good', 2026),
    ('Pittsburgh', 'Pat Narduzzi', 'Average', null::integer),
    ('Purdue', 'Barry Odom', 'Unknown', 2025),
    ('Rice', 'Scott Abell', 'Good', 2025),
    ('Rutgers', 'Greg Schiano', 'Average', null::integer),
    ('SMU', 'Rhett Lashley', 'Average', null::integer),
    ('Sam Houston', 'Phil Longo', 'Average', 2025),
    ('San Diego State', 'Sean Lewis', 'Average', 2024),
    ('San José State', 'Ken Niumatalolo', 'Average', 2024),
    ('South Alabama', 'Major Applewhite', 'Average', 2024),
    ('South Carolina', 'Shane Beamer', 'Average', null::integer),
    ('South Florida', 'Brian Hartline', 'Unknown', 2026),
    ('Southern Miss', 'Blake Anderson', 'Unknown', 2026),
    ('Stanford', 'Tavita Pritchard', 'Unknown', 2026),
    ('Syracuse', 'Fran Brown', 'Average', 2024),
    ('TCU', 'Sonny Dykes', 'Average', null::integer),
    ('Temple', 'KC Keeler', 'Good', 2025),
    ('Tennessee', 'Josh Heupel', 'Average', null::integer),
    ('Texas', 'Steve Sarkisian', 'Elite', null::integer),
    ('Texas A&M', 'Mike Elko', 'Elite', 2024),
    ('Texas State', 'GJ Kinne', 'Good', 2023),
    ('Texas Tech', 'Joey McGuire', 'Elite', null::integer),
    ('Toledo', 'Mke Jacobs', 'Average', null::integer),
    ('Troy', 'Gerad Parker', 'Average', 2024),
    ('Tulane', 'Will Hall', 'Unknown', 2026),
    ('Tulsa', 'Tre Lamb', 'Average', 2025),
    ('UAB', 'Alex Mortensen', 'Unknown', 2026),
    ('UCF', 'Scott Frost', 'Good', 2025),
    ('UCLA', 'Bob Chesney', 'Good', 2026),
    ('UConn', 'Jason Candle', 'Unknown', 2026),
    ('UL Monroe', 'Bryant Vincent', 'Average', 2024),
    ('UNLV', 'Dan Mullen', 'Good', 2025),
    ('USC', 'Lincoln Riley', 'Good', null::integer),
    ('UTEP', 'Scotty Walden', 'Average', 2024),
    ('UTSA', 'Jeff Traylor', 'Average', null::integer),
    ('Utah', 'Morgan Scalley', 'Unknown', 2026),
    ('Utah State', 'Bronco Mendenhall', 'Good', 2025),
    ('Vanderbilt', 'Clark Lea', 'Good', null::integer),
    ('Virginia', 'Tony Elliott', 'Average', null::integer),
    ('Virginia Tech', 'James Franklin', 'Elite', 2026),
    ('Wake Forest', 'Jake Dickert', 'Good', 2025),
    ('Washington', 'Jedd Fisch', 'Good', 2024),
    ('Washington State', 'Kirby Moore', 'Average', null::integer),
    ('West Virginia', 'Rich Rodriguez', 'Good', 2025),
    ('Western Kentucky', 'Tyson Helton', 'Average', null::integer),
    ('Western Michigan', 'Lance Taylor', 'Good', 2023),
    ('Wisconsin', 'Luke Fickell', 'Concerning', 2023),
    ('Wyoming', 'Jay Sawvel', 'Average', 2024)
),
normalized as (
  select
    team,
    coach_name,
    legacy_tier,
    hire_year,
    case
      when legacy_tier = 'Elite' then 'Elite'
      when legacy_tier = 'Good' then 'Good'
      when legacy_tier = 'Concerning' then 'Poor'
      else 'Average'
    end as development_rating
  from input
)
insert into public.coach_configs (
  team,
  coach_name,
  tier,
  hire_year,
  offense_rating,
  defense_rating,
  development_rating,
  source,
  updated_at
)
select
  team,
  coach_name,
  legacy_tier,
  hire_year,
  5,
  5,
  development_rating,
  'manual',
  now()
from normalized
on conflict (team) do update set
  coach_name = excluded.coach_name,
  tier = excluded.tier,
  hire_year = excluded.hire_year,
  development_rating = excluded.development_rating,
  source = 'manual',
  updated_at = now();
