-- Seed On3 roster source URLs for the CFB model.
-- Paste this whole file into Supabase SQL Editor and click Run.
-- It inserts every mapped FBS team for 2022-2025 and only Power 4 + Notre Dame for 2026.

with all_fbs(team, slug) as (
values
  ('Air Force', 'air-force-falcons'),
  ('Akron', 'akron-zips'),
  ('Alabama', 'alabama-crimson-tide'),
  ('Appalachian State', 'appalachian-state-mountaineers'),
  ('Arizona', 'arizona-wildcats'),
  ('Arizona State', 'arizona-state-sun-devils'),
  ('Arkansas', 'arkansas-razorbacks'),
  ('Arkansas State', 'arkansas-state-red-wolves'),
  ('Army', 'army-black-knights'),
  ('Auburn', 'auburn-tigers'),
  ('Ball State', 'ball-state-cardinals'),
  ('Baylor', 'baylor-bears'),
  ('Boise State', 'boise-state-broncos'),
  ('Boston College', 'boston-college-eagles'),
  ('Bowling Green', 'bowling-green-falcons'),
  ('Buffalo', 'buffalo-bulls'),
  ('BYU', 'byu-cougars'),
  ('California', 'california-golden-bears'),
  ('Central Michigan', 'central-michigan-chippewas'),
  ('Charlotte', 'charlotte-49ers'),
  ('Cincinnati', 'cincinnati-bearcats'),
  ('Clemson', 'clemson-tigers'),
  ('Coastal Carolina', 'coastal-carolina-chanticleers'),
  ('Colorado', 'colorado-buffaloes'),
  ('Colorado State', 'colorado-state-rams'),
  ('Connecticut', 'connecticut-huskies'),
  ('Duke', 'duke-blue-devils'),
  ('East Carolina', 'east-carolina-pirates'),
  ('Eastern Michigan', 'eastern-michigan-eagles'),
  ('Florida', 'florida-gators'),
  ('Florida Atlantic', 'florida-atlantic-owls'),
  ('Florida International', 'florida-international-panthers'),
  ('Florida State', 'florida-state-seminoles'),
  ('Fresno State', 'fresno-state-bulldogs'),
  ('Georgia', 'georgia-bulldogs'),
  ('Georgia Southern', 'georgia-southern-eagles'),
  ('Georgia State', 'georgia-state-panthers'),
  ('Georgia Tech', 'georgia-tech-yellow-jackets'),
  ('Hawaii', 'hawaii-rainbow-warriors'),
  ('Houston', 'houston-cougars'),
  ('Illinois', 'illinois-fighting-illini'),
  ('Indiana', 'indiana-hoosiers'),
  ('Iowa', 'iowa-hawkeyes'),
  ('Iowa State', 'iowa-state-cyclones'),
  ('Jacksonville State', 'jacksonville-state-gamecocks'),
  ('James Madison', 'james-madison-dukes'),
  ('Kansas', 'kansas-jayhawks'),
  ('Kansas State', 'kansas-state-wildcats'),
  ('Kennesaw State', 'kennesaw-state-owls'),
  ('Kent State', 'kent-state-golden-flashes'),
  ('Kentucky', 'kentucky-wildcats'),
  ('Liberty', 'liberty-flames'),
  ('Louisiana Lafayette', 'louisiana-ragin-cajuns'),
  ('Louisiana Monroe', 'louisiana-monroe-warhawks'),
  ('Louisiana Tech', 'louisiana-tech-bulldogs'),
  ('Louisville', 'louisville-cardinals'),
  ('LSU', 'lsu-tigers'),
  ('Marshall', 'marshall-thundering-herd'),
  ('Maryland', 'maryland-terrapins'),
  ('Massachusetts', 'massachusetts-minutemen'),
  ('Memphis', 'memphis-tigers'),
  ('Miami', 'miami-hurricanes'),
  ('Miami Ohio', 'miami-ohio-redhawks'),
  ('Michigan', 'michigan-wolverines'),
  ('Michigan State', 'michigan-state-spartans'),
  ('Middle Tennessee', 'middle-tennessee-blue-raiders'),
  ('Minnesota', 'minnesota-golden-gophers'),
  ('Mississippi State', 'mississippi-state-bulldogs'),
  ('Missouri', 'missouri-tigers'),
  ('Navy', 'navy-midshipmen'),
  ('NC State', 'nc-state-wolfpack'),
  ('Nebraska', 'nebraska-cornhuskers'),
  ('Nevada', 'nevada-wolf-pack'),
  ('New Mexico', 'new-mexico-lobos'),
  ('New Mexico State', 'new-mexico-state-aggies'),
  ('North Carolina', 'north-carolina-tar-heels'),
  ('North Texas', 'north-texas-mean-green'),
  ('Northern Illinois', 'northern-illinois-huskies'),
  ('Northwestern', 'northwestern-wildcats'),
  ('Notre Dame', 'notre-dame-fighting-irish'),
  ('Ohio', 'ohio-bobcats'),
  ('Ohio State', 'ohio-state-buckeyes'),
  ('Oklahoma', 'oklahoma-sooners'),
  ('Oklahoma State', 'oklahoma-state-cowboys'),
  ('Old Dominion', 'old-dominion-monarchs'),
  ('Ole Miss', 'ole-miss-rebels'),
  ('Oregon', 'oregon-ducks'),
  ('Oregon State', 'oregon-state-beavers'),
  ('Penn State', 'penn-state-nittany-lions'),
  ('Pittsburgh', 'pittsburgh-panthers'),
  ('Purdue', 'purdue-boilermakers'),
  ('Rice', 'rice-owls'),
  ('Rutgers', 'rutgers-scarlet-knights'),
  ('Sam Houston State', 'sam-houston-state-bearkats'),
  ('San Diego State', 'san-diego-state-aztecs'),
  ('San Jose State', 'san-jose-state-spartans'),
  ('SMU', 'smu-mustangs'),
  ('South Alabama', 'south-alabama-jaguars'),
  ('South Carolina', 'south-carolina-gamecocks'),
  ('South Florida', 'south-florida-bulls'),
  ('Southern Miss', 'southern-miss-golden-eagles'),
  ('Stanford', 'stanford-cardinal'),
  ('Syracuse', 'syracuse-orange'),
  ('TCU', 'tcu-horned-frogs'),
  ('Temple', 'temple-owls'),
  ('Tennessee', 'tennessee-volunteers'),
  ('Texas', 'texas-longhorns'),
  ('Texas A&M', 'texas-am-aggies'),
  ('Texas State', 'texas-state-bobcats'),
  ('Texas Tech', 'texas-tech-red-raiders'),
  ('Toledo', 'toledo-rockets'),
  ('Troy', 'troy-trojans'),
  ('Tulane', 'tulane-green-wave'),
  ('Tulsa', 'tulsa-golden-hurricane'),
  ('UAB', 'uab-blazers'),
  ('UCF', 'ucf-knights'),
  ('UCLA', 'ucla-bruins'),
  ('UNLV', 'unlv-rebels'),
  ('USC', 'usc-trojans'),
  ('Utah', 'utah-utes'),
  ('Utah State', 'utah-state-aggies'),
  ('UTEP', 'utep-miners'),
  ('UTSA', 'utsa-roadrunners'),
  ('Vanderbilt', 'vanderbilt-commodores'),
  ('Virginia', 'virginia-cavaliers'),
  ('Virginia Tech', 'virginia-tech-hokies'),
  ('Wake Forest', 'wake-forest-demon-deacons'),
  ('Washington', 'washington-huskies'),
  ('Washington State', 'washington-state-cougars'),
  ('West Virginia', 'west-virginia-mountaineers'),
  ('Western Kentucky', 'western-kentucky-hilltoppers'),
  ('Western Michigan', 'western-michigan-broncos'),
  ('Wisconsin', 'wisconsin-badgers'),
  ('Wyoming', 'wyoming-cowboys')
),
power4_2026(team, slug) as (
values
  ('Alabama', 'alabama-crimson-tide'),
  ('Arizona', 'arizona-wildcats'),
  ('Arizona State', 'arizona-state-sun-devils'),
  ('Arkansas', 'arkansas-razorbacks'),
  ('Auburn', 'auburn-tigers'),
  ('Baylor', 'baylor-bears'),
  ('Boston College', 'boston-college-eagles'),
  ('BYU', 'byu-cougars'),
  ('California', 'california-golden-bears'),
  ('Cincinnati', 'cincinnati-bearcats'),
  ('Clemson', 'clemson-tigers'),
  ('Colorado', 'colorado-buffaloes'),
  ('Duke', 'duke-blue-devils'),
  ('Florida', 'florida-gators'),
  ('Florida State', 'florida-state-seminoles'),
  ('Georgia', 'georgia-bulldogs'),
  ('Georgia Tech', 'georgia-tech-yellow-jackets'),
  ('Houston', 'houston-cougars'),
  ('Illinois', 'illinois-fighting-illini'),
  ('Indiana', 'indiana-hoosiers'),
  ('Iowa', 'iowa-hawkeyes'),
  ('Iowa State', 'iowa-state-cyclones'),
  ('Kansas', 'kansas-jayhawks'),
  ('Kansas State', 'kansas-state-wildcats'),
  ('Kentucky', 'kentucky-wildcats'),
  ('Louisville', 'louisville-cardinals'),
  ('LSU', 'lsu-tigers'),
  ('Maryland', 'maryland-terrapins'),
  ('Miami', 'miami-hurricanes'),
  ('Michigan', 'michigan-wolverines'),
  ('Michigan State', 'michigan-state-spartans'),
  ('Minnesota', 'minnesota-golden-gophers'),
  ('Mississippi State', 'mississippi-state-bulldogs'),
  ('Missouri', 'missouri-tigers'),
  ('NC State', 'nc-state-wolfpack'),
  ('Nebraska', 'nebraska-cornhuskers'),
  ('North Carolina', 'north-carolina-tar-heels'),
  ('Northwestern', 'northwestern-wildcats'),
  ('Notre Dame', 'notre-dame-fighting-irish'),
  ('Ohio State', 'ohio-state-buckeyes'),
  ('Oklahoma', 'oklahoma-sooners'),
  ('Oklahoma State', 'oklahoma-state-cowboys'),
  ('Ole Miss', 'ole-miss-rebels'),
  ('Oregon', 'oregon-ducks'),
  ('Penn State', 'penn-state-nittany-lions'),
  ('Pittsburgh', 'pittsburgh-panthers'),
  ('Purdue', 'purdue-boilermakers'),
  ('Rutgers', 'rutgers-scarlet-knights'),
  ('SMU', 'smu-mustangs'),
  ('South Carolina', 'south-carolina-gamecocks'),
  ('Stanford', 'stanford-cardinal'),
  ('Syracuse', 'syracuse-orange'),
  ('TCU', 'tcu-horned-frogs'),
  ('Tennessee', 'tennessee-volunteers'),
  ('Texas', 'texas-longhorns'),
  ('Texas A&M', 'texas-am-aggies'),
  ('Texas Tech', 'texas-tech-red-raiders'),
  ('UCF', 'ucf-knights'),
  ('UCLA', 'ucla-bruins'),
  ('USC', 'usc-trojans'),
  ('Utah', 'utah-utes'),
  ('Vanderbilt', 'vanderbilt-commodores'),
  ('Virginia', 'virginia-cavaliers'),
  ('Virginia Tech', 'virginia-tech-hokies'),
  ('Wake Forest', 'wake-forest-demon-deacons'),
  ('Washington', 'washington-huskies'),
  ('West Virginia', 'west-virginia-mountaineers'),
  ('Wisconsin', 'wisconsin-badgers')
),
seed_rows as (
  select season, team, 'https://www.on3.com/college/' || slug || '/football/' || season || '/roster/' as url, true as enabled
  from generate_series(2022, 2025) as season
  cross join all_fbs

  union all

  select 2026 as season, team, 'https://www.on3.com/college/' || slug || '/football/2026/roster/' as url, true as enabled
  from power4_2026
)
insert into public.on3_roster_sources (season, team, url, enabled)
select season, team, url, enabled
from seed_rows
on conflict (season, team)
do update set
  url = excluded.url,
  enabled = excluded.enabled,
  updated_at = now();

-- Quick check after running:
select season, count(*) as roster_source_count
from public.on3_roster_sources
group by season
order by season;
